CREATE TABLE `ggm_bsk`.`registrants` ( 
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`reg_type` SET('s','t') NOT NULL DEFAULT 's' , 
	`f_name` VARCHAR(64) NOT NULL , 
	`l_name` VARCHAR(64) NOT NULL , 
	`bday` DATE NOT NULL ,
	`age_group` SET('a','b','c','d', 'unassigned') NOT NULL DEFAULT 'unassigned' , 
	`address` VARCHAR(255) NOT NULL , 
	`city` VARCHAR(64) NOT NULL , 
	`zip` INT(20) NOT NULL , 
	`home_phone` VARCHAR(15) NULL , 
	`mobile_phone` VARCHAR(15) NULL , 
	`mother_name` VARCHAR(64) NULL , 
	`father_name` VARCHAR(64) NULL , 
	`email` VARCHAR(255) NOT NULL , 
	`emergency_contact` VARCHAR(64) NOT NULL , 
	`emergency_phone` VARCHAR(15) NOT NULL , 
	`medical_conditions` TEXT NULL, 
	`paid` TINYINT(1) NOT NULL DEFAULT '0',
	`last_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`waiver_signed` TINYINT(1) NOT NULL DEFAULT '0' ,
	`grade` SET('k','1','2','3','4','5','6','7','8','9','10','11','12','missing') NOT NULL DEFAULT 'missing' ,
	`team` SET('1','2','3','4','unassigned') NOT NULL DEFAULT 'unassigned' ,
	`enrollment_status` TINYINT(1) NOT NULL DEFAULT '0',	
	PRIMARY KEY (`id`)
) ENGINE = InnoDB;